@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.access_token}}
@questionId = {{get_question_by_slug.response.body.question.id}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Kaio Felipe",
    "email": "kaiofelps@teste.com",
    "password": "123456"
}

### 

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "kaiofelps@teste.com",
    "password": "123456"
}

### 

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "novas perguntas 3",
    "content": "conteúdo da pergunta 2"
}

### 

# @name fetch_recent_questions
GET {{baseUrl}}/questions?
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_question_by_slug
GET {{baseUrl}}/questions/novas-perguntas-3
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 

# @name answer_question
POST {{baseUrl}}/questions/{{questionId}}/answer
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "content": "conteúdo de criação da resposta"
}
