@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Kaio Felipe",
    "email": "kaiofelps@teste.com",
    "password": "123456"
}

### 

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "kaiofelps@teste.com",
    "password": "123456"
}

### 

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "novas perguntas 2",
    "content": "conteúdo da pergunta 2"
}

### 

# @name fetch_recent_questions
GET {{baseUrl}}/questions?
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "nova pergunta",
    "content": "conteúdo da perguntaa"
}

###

# @name get_question_by_slug
GET {{baseUrl}}/questions/nova-perguntas-1
Content-Type: application/json
Authorization: Bearer {{authToken}}